### basic settings

# site properties and page defaults
title: Drake Williams DDS, PhD
description: A dentist scientist studying oral barrier immunity
logo: images/logo.png
header: 
footer: 
baseurl: ""

# site social media and other links
links:
  email: drakewilliams@gmail.com
  orcid: 0000-0002-7718-2098
  google-scholar: 6SmnW4IAAAA
  github: williamsdrake
  twitter: drake_dds
  
twitter:
  username: drake_dds

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: orcid
      input:
        - ../_data/orcid.yaml
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# Google Analytics:
google_analytics: UA-216067793-1

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
